services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/config:/config
      - ./data/database:/data
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - sqlite-network # Assign the service to the network

networks:
  sqlite-network: # Define the network